resources:
  - manager.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
  - name: ghcr.io/aclerici38/pocket-id-operator
    newName: ghcr.io/aclerici38/pocket-id-operator
    newTag: v0.4.7@sha256:8aa2109888894b67e05b082c6c1ed7b6662a403eb59a8e162cfd46818d50bab0