resources:
  - manager.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
  - name: ghcr.io/aclerici38/pocket-id-operator
    newName: ghcr.io/aclerici38/pocket-id-operator
    newTag: v0.7.1@sha256:266d908a020aaa70f61cb6392afccb269763bd9cb99d23fa00376178e4ace41e