resources:
  - manager.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
  - name: ghcr.io/aclerici38/pocket-id-operator
    newName: ghcr.io/aclerici38/pocket-id-operator
    newTag: v0.13.1@sha256:63b4ef346945c27282adcbdf3e1d22891b40a1bf873cb599881d9ca50fe0ea4b
