package oidcclient

import (
	"context"
	"fmt"

	corev1 "k8s.io/api/core/v1"
	"sigs.k8s.io/controller-runtime/pkg/client"
	logf "sigs.k8s.io/controller-runtime/pkg/log"

	pocketidinternalv1alpha1 "github.com/aclerici38/pocket-id-operator/api/v1alpha1"
	"github.com/aclerici38/pocket-id-operator/internal/pocketid"
)

// clientSecretMinLength mirrors Pocket-ID's minimum length for an explicitly set client secret.
const clientSecretMinLength = 16

// hasDeclaredClientSecret reports whether the client secret is supplied by the user via
// spec.clientSecretRef rather than generated by the operator. While true, the operator never
// generates or rotates the secret.
func hasDeclaredClientSecret(oidcClient *pocketidinternalv1alpha1.PocketIDOIDCClient) bool {
	return oidcClient.Spec.ClientSecretRef != nil
}

// validateClientSecret mirrors Pocket-ID's own constraints (at least 16 printable ASCII
// characters) so a bad value surfaces on the CR instead of as an opaque 400 from the API.
func validateClientSecret(secret string) error {
	if len(secret) < clientSecretMinLength {
		return fmt.Errorf("client secret must be at least %d characters", clientSecretMinLength)
	}
	for _, c := range secret {
		if c < 0x20 || c > 0x7e {
			return fmt.Errorf("client secret must contain only printable ASCII characters")
		}
	}
	return nil
}

// resolveDeclaredClientSecret reads the secret referenced by spec.clientSecretRef and returns it
// alongside a version string identifying the source revision. The referenced Secret is not
// operator-managed, so it is absent from the label-filtered cache and must be read via APIReader.
func (r *Reconciler) resolveDeclaredClientSecret(ctx context.Context, oidcClient *pocketidinternalv1alpha1.PocketIDOIDCClient) (secret, version string, err error) {
	ref := oidcClient.Spec.ClientSecretRef
	if ref.Name == r.GetSecretName(oidcClient) {
		return "", "", fmt.Errorf("spec.clientSecretRef must not reference the operator-managed secret %q", ref.Name)
	}

	source := &corev1.Secret{}
	if err := r.APIReader.Get(ctx, client.ObjectKey{Namespace: oidcClient.Namespace, Name: ref.Name}, source); err != nil {
		return "", "", fmt.Errorf("get client secret %s: %w", ref.Name, err)
	}

	value, ok := source.Data[ref.Key]
	if !ok {
		return "", "", fmt.Errorf("secret %s missing key %s", ref.Name, ref.Key)
	}
	if err := validateClientSecret(string(value)); err != nil {
		return "", "", err
	}

	return string(value), fmt.Sprintf("%s/%s@%s", ref.Name, ref.Key, source.ResourceVersion), nil
}

// SyncDeclaredClientSecret pushes the secret referenced by spec.clientSecretRef whenever the
// source revision differs from the one last pushed. Pocket-ID stores the secret hashed and never
// returns it, so that revision is the only way to tell a push is needed. This runs independently
// of ReconcileSecret so the declared secret still reaches Pocket-ID when spec.secret.enabled is
// false, which is also why it handles its own retirement.
func (r *Reconciler) SyncDeclaredClientSecret(ctx context.Context, oidcClient *pocketidinternalv1alpha1.PocketIDOIDCClient, apiClient PocketIDOIDCClientAPI, observed []pocketid.OIDCClientSecret) error {
	if !hasDeclaredClientSecret(oidcClient) {
		// The ref was removed; drop the stale record so re-adding it pushes again.
		if oidcClient.Status.ClientSecretSourceVersion != "" {
			return r.ClearStatusField(ctx, oidcClient, func() {
				oidcClient.Status.ClientSecretSourceVersion = ""
			})
		}
		return nil
	}
	if oidcClient.Status.ClientID == "" {
		return nil
	}

	secret, version, err := r.resolveDeclaredClientSecret(ctx, oidcClient)
	if err != nil {
		return err
	}

	// The source revision says whether the value needs pushing, but not whether it survived: one
	// deleted out-of-band leaves the client unable to authenticate. Push again to restore it.
	missing := !clientSecretPresent(secret, observed)

	var minted *pocketid.OIDCClientSecret
	if version != oidcClient.Status.ClientSecretSourceVersion || missing {
		logf.FromContext(ctx).Info("Setting declared client secret",
			"name", oidcClient.Name, "clientID", oidcClient.Status.ClientID, "restoring", missing)

		if err := r.makeRoomForClientSecret(ctx, oidcClient, apiClient,
			resolveClientSecret(oidcClient.Status.ClientSecretID, secret, observed), observed); err != nil {
			return err
		}

		created, returned, err := apiClient.CreateOIDCClientSecret(ctx, oidcClient.Status.ClientID, secret)
		if err != nil {
			return fmt.Errorf("create client secret: %w", err)
		}
		// The declared value is what gets mirrored into the managed Secret, so a Pocket-ID that
		// stored something else would leave the two disagreeing with nothing to detect it later.
		if returned != secret {
			return fmt.Errorf("pocket-id stored a generated client secret instead of the declared one")
		}

		base := oidcClient.DeepCopy()
		oidcClient.Status.ClientSecretSourceVersion = version
		oidcClient.Status.ClientSecretID = created.ID
		if err := r.Status().Patch(ctx, oidcClient, client.MergeFrom(base)); err != nil {
			return err
		}
		minted = &created
	}

	// Safe to retire immediately: the declared value's durability is the referenced Secret's
	// concern. Also runs without a push, to finish a retirement the overlap was holding open.
	return r.reconcileClientSecretRetention(ctx, oidcClient, apiClient, observed, minted, secret)
}
