package pocketid

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"time"
)

// BootstrapClient handles the initial setup of a Pocket-ID instance.
// This is separate from Client because the setup endpoint requires
// capturing cookies from the response, which the autogenerated swagger client doesn't support well.
type BootstrapClient struct {
	baseURL    string
	httpClient *http.Client
}

// SetupRequest contains the data for initial admin setup.
type SetupRequest struct {
	Username  string `json:"username"`
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName,omitempty"`
	Email     string `json:"email,omitempty"`
}

type SetupResponse struct {
	ID          string `json:"id"`
	Username    string `json:"username"`
	FirstName   string `json:"firstName"`
	LastName    string `json:"lastName"`
	Email       string `json:"email"`
	DisplayName string `json:"displayName"`
	IsAdmin     bool   `json:"isAdmin"`
}

type CreateAPIKeyRequest struct {
	Name        string `json:"name"`
	ExpiresAt   string `json:"expiresAt"`
	Description string `json:"description,omitempty"`
}

// CreateAPIKeyResponse contains the API key data including the token.
type CreateAPIKeyResponse struct {
	APIKey struct {
		ID          string `json:"id"`
		Name        string `json:"name"`
		Description string `json:"description"`
		CreatedAt   string `json:"createdAt"`
		ExpiresAt   string `json:"expiresAt"`
	} `json:"apiKey"`
	Token string `json:"token"`
}

func NewBootstrapClient(baseURL string) *BootstrapClient {
	return &BootstrapClient{
		baseURL: baseURL,
		httpClient: &http.Client{
			Timeout: 10 * time.Second,
		},
	}
}

// Setup creates the initial admin user on a fresh Pocket-ID instance.
// Returns the created user and the session cookies for subsequent requests.
func (b *BootstrapClient) Setup(ctx context.Context, req SetupRequest) (*SetupResponse, []*http.Cookie, error) {
	body, err := json.Marshal(req)
	if err != nil {
		return nil, nil, fmt.Errorf("marshal request: %w", err)
	}

	httpReq, err := http.NewRequestWithContext(ctx, http.MethodPost, b.baseURL+"/api/signup/setup", bytes.NewReader(body))
	if err != nil {
		return nil, nil, fmt.Errorf("create request: %w", err)
	}
	httpReq.Header.Set("Content-Type", "application/json")

	resp, err := b.httpClient.Do(httpReq)
	if err != nil {
		return nil, nil, fmt.Errorf("execute request: %w", err)
	}
	defer func() { _ = resp.Body.Close() }()

	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, nil, fmt.Errorf("read response: %w", err)
	}

	if resp.StatusCode != http.StatusOK {
		return nil, nil, fmt.Errorf("setup failed with status %d: %s", resp.StatusCode, string(respBody))
	}

	var setupResp SetupResponse
	if err := json.Unmarshal(respBody, &setupResp); err != nil {
		return nil, nil, fmt.Errorf("unmarshal response: %w", err)
	}

	return &setupResp, resp.Cookies(), nil
}

func (b *BootstrapClient) CreateAPIKeyWithCookies(ctx context.Context, cookies []*http.Cookie, req CreateAPIKeyRequest) (*CreateAPIKeyResponse, error) {
	body, err := json.Marshal(req)
	if err != nil {
		return nil, fmt.Errorf("marshal request: %w", err)
	}

	httpReq, err := http.NewRequestWithContext(ctx, http.MethodPost, b.baseURL+"/api/api-keys", bytes.NewReader(body))
	if err != nil {
		return nil, fmt.Errorf("create request: %w", err)
	}
	httpReq.Header.Set("Content-Type", "application/json")

	for _, cookie := range cookies {
		httpReq.AddCookie(cookie)
	}

	resp, err := b.httpClient.Do(httpReq)
	if err != nil {
		return nil, fmt.Errorf("execute request: %w", err)
	}
	defer func() { _ = resp.Body.Close() }()

	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response: %w", err)
	}

	if resp.StatusCode != http.StatusCreated {
		return nil, fmt.Errorf("create API key failed with status %d: %s", resp.StatusCode, string(respBody))
	}

	var apiKeyResp CreateAPIKeyResponse
	if err := json.Unmarshal(respBody, &apiKeyResp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}

	return &apiKeyResp, nil
}

// Bootstrap performs the complete bootstrap flow:
// 1. Creates the initial admin user
// 2. Creates an API key for the operator
// Returns the user, API key details, and the API key token.
func (b *BootstrapClient) Bootstrap(ctx context.Context, user SetupRequest, apiKeyName, apiKeyDescription string, apiKeyExpiry time.Time) (*SetupResponse, *CreateAPIKeyResponse, error) {
	// Setup initial admin
	setupResp, cookies, err := b.Setup(ctx, user)
	if err != nil {
		return nil, nil, fmt.Errorf("setup: %w", err)
	}

	if len(cookies) == 0 {
		return nil, nil, fmt.Errorf("no session cookies returned from setup")
	}

	// Create API key
	apiKeyReq := CreateAPIKeyRequest{
		Name:        apiKeyName,
		ExpiresAt:   apiKeyExpiry.Format(time.RFC3339),
		Description: apiKeyDescription,
	}

	apiKeyResp, err := b.CreateAPIKeyWithCookies(ctx, cookies, apiKeyReq)
	if err != nil {
		return nil, nil, fmt.Errorf("create API key: %w", err)
	}

	return setupResp, apiKeyResp, nil
}

// DefaultAPIKeyExpiry returns a default expiry time (10 years from now).
func DefaultAPIKeyExpiry() time.Time {
	return time.Now().AddDate(10, 0, 0)
}
