package pocketid

import (
	"context"
	"fmt"
	"net/http"
	"time"
)

// BootstrapClient handles the initial setup of a Pocket-ID instance.
// This is separate from Client because the setup endpoint requires
// capturing cookies from the response, which the autogenerated swagger client doesn't support well.
type BootstrapClient struct {
	baseURL    string
	httpClient *http.Client
	session    *sessionClient
}

// SetupRequest contains the data for initial admin setup.
type SetupRequest struct {
	Username  string `json:"username"`
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName,omitempty"`
	Email     string `json:"email,omitempty"`
}

type SetupResponse struct {
	ID          string `json:"id"`
	Username    string `json:"username"`
	FirstName   string `json:"firstName"`
	LastName    string `json:"lastName"`
	Email       string `json:"email"`
	DisplayName string `json:"displayName"`
	IsAdmin     bool   `json:"isAdmin"`
}

type CreateAPIKeyRequest struct {
	Name        string `json:"name"`
	ExpiresAt   string `json:"expiresAt"`
	Description string `json:"description,omitempty"`
}

// CreateAPIKeyResponse contains the API key data including the token.
type CreateAPIKeyResponse struct {
	APIKey struct {
		ID          string `json:"id"`
		Name        string `json:"name"`
		Description string `json:"description"`
		CreatedAt   string `json:"createdAt"`
		ExpiresAt   string `json:"expiresAt"`
	} `json:"apiKey"`
	Token string `json:"token"`
}

func NewBootstrapClient(baseURL string) *BootstrapClient {
	httpClient := &http.Client{
		Timeout: 10 * time.Second,
	}
	return &BootstrapClient{
		baseURL:    baseURL,
		httpClient: httpClient,
		session:    newSessionClient(baseURL, httpClient),
	}
}

// Setup creates the initial admin user on a fresh Pocket-ID instance.
// Returns the created user and the session cookies for subsequent requests.
func (b *BootstrapClient) Setup(ctx context.Context, req SetupRequest) (*SetupResponse, []*http.Cookie, error) {
	return b.session.setup(ctx, req)
}

func (b *BootstrapClient) CreateAPIKeyWithCookies(ctx context.Context, cookies []*http.Cookie, req CreateAPIKeyRequest) (*CreateAPIKeyResponse, error) {
	return b.session.createAPIKeyWithCookies(ctx, cookies, req)
}

// Bootstrap performs the complete bootstrap flow:
// 1. Creates the initial admin user
// 2. Creates an API key for the operator
// Returns the user, API key details, and the API key token.
func (b *BootstrapClient) Bootstrap(ctx context.Context, user SetupRequest, apiKeyName, apiKeyDescription string, apiKeyExpiry time.Time) (*SetupResponse, *CreateAPIKeyResponse, error) {
	// Setup initial admin
	setupResp, cookies, err := b.Setup(ctx, user)
	if err != nil {
		return nil, nil, fmt.Errorf("setup: %w", err)
	}

	if len(cookies) == 0 {
		return nil, nil, fmt.Errorf("no session cookies returned from setup")
	}

	// Create API key
	apiKeyReq := CreateAPIKeyRequest{
		Name:        apiKeyName,
		ExpiresAt:   apiKeyExpiry.Format(time.RFC3339),
		Description: apiKeyDescription,
	}

	apiKeyResp, err := b.CreateAPIKeyWithCookies(ctx, cookies, apiKeyReq)
	if err != nil {
		return nil, nil, fmt.Errorf("create API key: %w", err)
	}

	return setupResp, apiKeyResp, nil
}

// DefaultAPIKeyExpiry returns a default expiry time (10 years from now).
func DefaultAPIKeyExpiry() time.Time {
	return time.Now().AddDate(10, 0, 0)
}
