// Package pocketid provides a clean wrapper around the Pocket-ID API client.
package pocketid

import (
	"context"
	"crypto/tls"
	"encoding/base64"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"sort"
	"strings"
	"time"

	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	apiclient "github.com/aclerici38/pocket-id-go-client/v2/client"
	"github.com/aclerici38/pocket-id-go-client/v2/client/api_keys"
	"github.com/aclerici38/pocket-id-go-client/v2/client/apis"
	custom_claims "github.com/aclerici38/pocket-id-go-client/v2/client/custom_claims"
	oidc "github.com/aclerici38/pocket-id-go-client/v2/client/o_id_c"
	scim "github.com/aclerici38/pocket-id-go-client/v2/client/s_c_i_m"
	"github.com/aclerici38/pocket-id-go-client/v2/client/user_groups"
	"github.com/aclerici38/pocket-id-go-client/v2/client/users"
	pocketidversion "github.com/aclerici38/pocket-id-go-client/v2/client/version"
	"github.com/aclerici38/pocket-id-go-client/v2/models"
)

// Client wraps the autogenerated Pocket-ID API client with a cleaner interface.
// Each client is immutable after creation.
type Client struct {
	raw     *apiclient.PocketIDAPI
	baseURL string
	// httpClient is nil unless an option customized transport behavior, in which case
	// the session-auth calls reuse it so they reach the instance the same way.
	httpClient *http.Client
}

// ClientOption customizes a Client at construction time.
type ClientOption func(*Client)

// WithTLSConfig makes the client use cfg for HTTPS connections. A nil cfg is a no-op,
// leaving Go's default verification against the system trust store in place.
func WithTLSConfig(cfg *tls.Config) ClientOption {
	return func(c *Client) {
		if cfg == nil {
			return
		}
		transport := http.DefaultTransport.(*http.Transport).Clone()
		transport.TLSClientConfig = cfg
		c.httpClient = &http.Client{Transport: transport}
	}
}

// User represents a Pocket-ID user with clean field names.
type User struct {
	ID            string
	Username      string
	FirstName     string
	LastName      string
	Email         string
	DisplayName   string
	IsAdmin       bool
	Disabled      bool
	Locale        string
	EmailVerified bool
	CustomClaims  []CustomClaim
}

// APIKey represents a Pocket-ID API key.
type APIKey struct {
	ID          string
	Name        string
	Description string
	CreatedAt   string
	ExpiresAt   string
	LastUsedAt  string
}

// APIKeyWithToken is returned when creating an API key. The token is a one-time token.
type APIKeyWithToken struct {
	APIKey
	Token string
}

// OIDCClient represents an OIDC client with key configuration.
type OIDCClient struct {
	ID                                  string
	Name                                string
	Description                         string
	CallbackURLs                        []string
	LogoutCallbackURLs                  []string
	LaunchURL                           string
	HasLogo                             bool
	HasDarkLogo                         bool
	IsPublic                            bool
	IsGroupRestricted                   bool
	PKCEEnabled                         bool
	PKCESupported                       bool
	RequiresReauthentication            bool
	RequiresPushedAuthorizationRequests bool
	SkipConsent                         bool
	AccessTokenDurationMinutes          int64
	RefreshTokenDurationMinutes         int64
	AllowedUserGroupIDs                 []string
	// ClientType is "standard" or "cimd". Read-only; Pocket-ID sets it at registration.
	ClientType string
	// Secrets is read-only; secrets are managed through the dedicated endpoints.
	Secrets []OIDCClientSecret
}

// OIDCClientSecret is one of a client's secrets. Its value is only ever returned by the call
// that creates it.
type OIDCClientSecret struct {
	ID string
	// Prefix is the leading clear-text characters of the value, empty for secrets Pocket-ID
	// migrated from the single-secret column it used before v2.14.0.
	Prefix    string
	CreatedAt time.Time
	// IsActive reports whether Pocket-ID still accepts the secret, i.e. it has not expired.
	// An inactive secret authenticates nothing but still counts against MaxOIDCClientSecrets.
	IsActive bool
}

const (
	// MaxOIDCClientSecrets is Pocket-ID's cap on secrets per client, expired ones included.
	MaxOIDCClientSecrets = 20

	// OIDCClientSecretPrefixLength is how much of a secret Pocket-ID keeps in clear text.
	OIDCClientSecretPrefixLength = 4
)

// SecretPrefix returns the prefix Pocket-ID would record for value, or "" if it is too short.
func SecretPrefix(value string) string {
	if len(value) <= OIDCClientSecretPrefixLength {
		return ""
	}
	return value[:OIDCClientSecretPrefixLength]
}

// ClientTypeCIMD marks a client synthesized from an OAuth Client ID Metadata Document.
// Its ID is the https URL of that document, and Pocket-ID persists only a subset of
// columns on an admin update, leaving the rest to the metadata refresh.
const ClientTypeCIMD = "cimd"

// IsCIMD reports whether the client is backed by an OAuth Client ID Metadata Document.
func (c *OIDCClient) IsCIMD() bool {
	return c.ClientType == ClientTypeCIMD
}

// LooksLikeCIMDID reports whether a client ID is a metadata document URL. Pocket-ID
// restricts registered client IDs to [a-zA-Z0-9._-]+, so an "https://" prefix can only come
// from a metadata document. Unlike IsCIMD this needs no API round trip, which is what makes
// it usable before a client has been resolved. It matches the CRD's CEL admission rules and
// upstream's fosite.LooksLikeCIMDURL, which both require the https scheme.
func LooksLikeCIMDID(id string) bool {
	return strings.HasPrefix(id, "https://")
}

// clientIDPathParam encodes a client ID for use as a URL path parameter. A CIMD client ID
// is a full https URL whose slashes cannot survive a single path segment, so Pocket-ID
// accepts it base64url-encoded behind a "~" prefix and decodes it in middleware. Ordinary
// client IDs are passed through untouched.
//
// Every call that takes an OIDC client ID as a path parameter must apply this;
// TestOIDCClientOperations_UseEncodedPathForMetadataDocumentIDs enumerates them.
func clientIDPathParam(id string) string {
	if !LooksLikeCIMDID(id) {
		return id
	}
	return "~" + base64.RawURLEncoding.EncodeToString([]byte(id))
}

// ToInput converts an OIDCClient into an OIDCClientInput for comparison with desired state.
// ID and Credentials are not included: federated identities aren't returned by the GET API, and
// the secrets it carries have their own endpoints.
// LogoURL and DarkLogoURL are write-only (not returned by the API); logo presence is
// tracked via HasLogo/HasDarkLogo instead.
// AllowedUserGroupIDs is managed separately and excluded from the input.
// PKCESupported is read-only (set by Pocket-ID, never pushed) and excluded from the input.
func (c *OIDCClient) ToInput() OIDCClientInput {
	return OIDCClientInput{
		Name:                                c.Name,
		Description:                         c.Description,
		CallbackURLs:                        c.CallbackURLs,
		LogoutCallbackURLs:                  c.LogoutCallbackURLs,
		LaunchURL:                           c.LaunchURL,
		HasLogo:                             c.HasLogo,
		HasDarkLogo:                         c.HasDarkLogo,
		IsPublic:                            c.IsPublic,
		IsGroupRestricted:                   c.IsGroupRestricted,
		PKCEEnabled:                         c.PKCEEnabled,
		RequiresReauthentication:            c.RequiresReauthentication,
		RequiresPushedAuthorizationRequests: c.RequiresPushedAuthorizationRequests,
		SkipConsent:                         c.SkipConsent,
		AccessTokenDurationMinutes:          c.AccessTokenDurationMinutes,
		RefreshTokenDurationMinutes:         c.RefreshTokenDurationMinutes,
	}
}

// OIDCClientFederatedIdentity represents a federated identity for OIDC clients.
type OIDCClientFederatedIdentity struct {
	Issuer           string
	Subject          string
	Audience         string
	JWKS             string
	ReplayProtection bool
}

// OIDCClientCredentials holds optional federated identity configuration.
type OIDCClientCredentials struct {
	FederatedIdentities []OIDCClientFederatedIdentity
}

// OIDCClientInput contains fields for creating or updating an OIDC client.
type OIDCClientInput struct {
	ID                                  *string // nil means let Pocket-ID autogenerate
	Name                                string
	Description                         string
	CallbackURLs                        []string
	LogoutCallbackURLs                  []string
	LaunchURL                           string
	LogoURL                             string
	DarkLogoURL                         string
	HasLogo                             bool
	HasDarkLogo                         bool
	IsPublic                            bool
	IsGroupRestricted                   bool
	PKCEEnabled                         bool
	RequiresReauthentication            bool
	RequiresPushedAuthorizationRequests bool
	SkipConsent                         bool
	AccessTokenDurationMinutes          int64
	RefreshTokenDurationMinutes         int64
	Credentials                         *OIDCClientCredentials
}

// Equal compares two OIDCClientInputs for equality on the fields that can be
// compared (excludes ID and Credentials which are create-time or write-only,
// and excludes LogoURL/DarkLogoURL which are not returned by the GET API —
// logo presence is compared via HasLogo/HasDarkLogo instead).
func (i OIDCClientInput) Equal(other OIDCClientInput) bool {
	if i.Name != other.Name ||
		i.Description != other.Description ||
		i.LaunchURL != other.LaunchURL ||
		i.HasLogo != other.HasLogo ||
		i.HasDarkLogo != other.HasDarkLogo ||
		i.IsPublic != other.IsPublic ||
		i.IsGroupRestricted != other.IsGroupRestricted ||
		i.PKCEEnabled != other.PKCEEnabled ||
		i.RequiresReauthentication != other.RequiresReauthentication ||
		i.RequiresPushedAuthorizationRequests != other.RequiresPushedAuthorizationRequests ||
		i.SkipConsent != other.SkipConsent ||
		i.AccessTokenDurationMinutes != other.AccessTokenDurationMinutes ||
		i.RefreshTokenDurationMinutes != other.RefreshTokenDurationMinutes {
		return false
	}
	if !orderedEqual(i.CallbackURLs, other.CallbackURLs) {
		return false
	}
	if !orderedEqual(i.LogoutCallbackURLs, other.LogoutCallbackURLs) {
		return false
	}
	return true
}

// CustomClaim represents a custom claim key/value pair.
type CustomClaim struct {
	Key   string
	Value string
}

// SCIMServiceProvider represents a SCIM service provider configuration linked to an OIDC client.
type SCIMServiceProvider struct {
	ID           string
	Endpoint     string
	Token        string
	OIDCClientID string
	CreatedAt    string
	LastSyncedAt string
}

// SCIMServiceProviderInput is used to create or update a SCIM service provider.
type SCIMServiceProviderInput struct {
	Endpoint     string
	OIDCClientID string
	Token        string
}

// UserGroup represents a Pocket-ID user group.
type UserGroup struct {
	ID                   string
	Name                 string
	FriendlyName         string
	CreatedAt            string
	LdapID               string
	UserCount            int
	UserIDs              []string
	CustomClaims         []CustomClaim
	AllowedOIDCClientIDs []string
}

// UserGroupInput contains the fields the operator manages for a user group.
// AllowedOIDCClientIDs is excluded because the OIDC client controller owns that relationship.
type UserGroupInput struct {
	Name         string
	FriendlyName string
	CustomClaims []CustomClaim
	UserIDs      []string
}

// ToInput converts a UserGroup into a UserGroupInput for comparison with desired state.
func (g *UserGroup) ToInput() UserGroupInput {
	return UserGroupInput{
		Name:         g.Name,
		FriendlyName: g.FriendlyName,
		CustomClaims: g.CustomClaims,
		UserIDs:      g.UserIDs,
	}
}

// CustomClaimsEqual compares two CustomClaim slices for equality regardless of order.
func CustomClaimsEqual(a, b []CustomClaim) bool {
	if len(a) == 0 && len(b) == 0 {
		return true
	}
	if len(a) != len(b) {
		return false
	}
	aMap := make(map[string]string, len(a))
	for _, c := range a {
		aMap[c.Key] = c.Value
	}
	for _, c := range b {
		if v, ok := aMap[c.Key]; !ok || v != c.Value {
			return false
		}
	}
	return true
}

func orderedEqual(a, b []string) bool {
	if len(a) == 0 && len(b) == 0 {
		return true
	}
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if a[i] != b[i] {
			return false
		}
	}
	return true
}

// SortedEqual compares two string slices for equality regardless of order.
func SortedEqual(a, b []string) bool {
	if len(a) == 0 && len(b) == 0 {
		return true
	}
	if len(a) != len(b) {
		return false
	}
	aCopy := make([]string, len(a))
	bCopy := make([]string, len(b))
	copy(aCopy, a)
	copy(bCopy, b)
	sort.Strings(aCopy)
	sort.Strings(bCopy)
	for i := range aCopy {
		if aCopy[i] != bCopy[i] {
			return false
		}
	}
	return true
}

// NewClient creates a new Pocket-ID client for the given base URL with optional API key.
func NewClient(baseURL string, apiKey string, opts ...ClientOption) (*Client, error) {
	parsed, err := url.Parse(baseURL)
	if err != nil {
		return nil, fmt.Errorf("parse base URL: %w", err)
	}

	c := &Client{baseURL: parsed.Scheme + "://" + parsed.Host}
	for _, opt := range opts {
		opt(c)
	}

	transport := httptransport.NewWithClient(parsed.Host, "/", []string{parsed.Scheme}, c.httpClient)

	if apiKey != "" {
		transport.DefaultAuthentication = runtime.ClientAuthInfoWriterFunc(
			func(req runtime.ClientRequest, reg strfmt.Registry) error {
				return req.SetHeaderParam("X-API-KEY", apiKey)
			},
		)
	}

	// Every operation declares a default error response, so go-swagger deserializes
	// error bodies instead of just recording the status code.
	for _, mime := range []string{runtime.TextMime, runtime.HTMLMime, runtime.DefaultMime} {
		transport.Consumers[mime] = discardingConsumer{}
	}

	c.raw = apiclient.New(transport, strfmt.Default)

	return c, nil
}

// discardingConsumer drains a response body without decoding it, so the surrounding
// response type (and its status code) survives a body it cannot parse.
type discardingConsumer struct{}

func (discardingConsumer) Consume(reader io.Reader, _ any) error {
	_, err := io.Copy(io.Discard, reader)
	return err
}

// --- Version Operations ---

// GetCurrentVersion returns the currently deployed version of the PocketID instance.
func (c *Client) GetCurrentVersion(ctx context.Context) (string, error) {
	params := pocketidversion.NewGetAPIVersionCurrentParams()
	start := time.Now()
	resp, err := c.raw.Version.GetAPIVersionCurrentContext(ctx, params)
	recordCall("get_current_version", err, time.Since(start))
	if err != nil {
		return "", fmt.Errorf("get current version failed: %w", err)
	}
	v, ok := resp.Payload["currentVersion"]
	if !ok {
		return "", fmt.Errorf("currentVersion key missing from response")
	}
	return v, nil
}

// --- User Operations ---

func (c *Client) GetUser(ctx context.Context, id string) (*User, error) {
	params := users.NewGetAPIUsersIDParams().
		WithID(id)

	start := time.Now()
	resp, err := c.raw.Users.GetAPIUsersIDContext(ctx, params)
	recordCall("get_user", err, time.Since(start))
	if err != nil {
		return nil, fmt.Errorf("get user failed: %w", err)
	}

	return userFromDTO(resp.Payload), nil
}

// ListUsers returns a list of users matching the search term.
// If search is empty, all users are returned.
func (c *Client) ListUsers(ctx context.Context, search string) ([]*User, error) {
	params := users.NewGetAPIUsersParams()

	if search != "" {
		params = params.WithSearch(&search)
	}

	start := time.Now()
	resp, err := c.raw.Users.GetAPIUsersContext(ctx, params)
	recordCall("list_users", err, time.Since(start))
	if err != nil {
		return nil, fmt.Errorf("list users failed: %w", err)
	}

	userList := make([]*User, 0, len(resp.Payload.Data))
	for _, dto := range resp.Payload.Data {
		userList = append(userList, userFromDTO(dto))
	}

	return userList, nil
}

// UserInput contains the fields for creating or updating a user.
type UserInput struct {
	// ID is honored by Pocket-ID on create only; an empty value autogenerates one.
	ID            string
	Username      string
	FirstName     string
	LastName      string
	Email         string
	DisplayName   string
	IsAdmin       bool
	Disabled      bool
	Locale        string
	EmailVerified bool
}

// Equal compares two UserInputs, ignoring ID because Pocket-ID assigns it at
// creation and never accepts a change to it.
func (i UserInput) Equal(other UserInput) bool {
	i.ID, other.ID = "", ""
	return i == other
}

// ToInput converts a User into a UserInput for comparison with desired state.
func (u *User) ToInput() UserInput {
	return UserInput{
		ID:            u.ID,
		Username:      u.Username,
		FirstName:     u.FirstName,
		LastName:      u.LastName,
		Email:         u.Email,
		DisplayName:   u.DisplayName,
		IsAdmin:       u.IsAdmin,
		Disabled:      u.Disabled,
		Locale:        u.Locale,
		EmailVerified: u.EmailVerified,
	}
}

func (c *Client) CreateUser(ctx context.Context, input UserInput) (*User, error) {
	params := users.NewPostAPIUsersParams().
		WithUser(&models.GithubComPocketIDPocketIDBackendInternalDtoUserCreateDto{
			ID:            input.ID,
			Username:      &input.Username,
			FirstName:     input.FirstName,
			LastName:      input.LastName,
			Email:         input.Email,
			DisplayName:   input.DisplayName,
			IsAdmin:       input.IsAdmin,
			Disabled:      input.Disabled,
			Locale:        input.Locale,
			EmailVerified: input.EmailVerified,
		})

	start := time.Now()
	resp, err := c.raw.Users.PostAPIUsersContext(ctx, params)
	recordCall("create_user", err, time.Since(start))
	if err != nil {
		return nil, fmt.Errorf("create user failed: %w", err)
	}

	return userFromDTO(resp.Payload), nil
}

// UpdateUser updates an existing user.
func (c *Client) UpdateUser(ctx context.Context, id string, input UserInput) (*User, error) {
	params := users.NewPutAPIUsersIDParams().
		WithID(id).
		WithUser(&models.GithubComPocketIDPocketIDBackendInternalDtoUserCreateDto{
			Username:      &input.Username,
			FirstName:     input.FirstName,
			LastName:      input.LastName,
			Email:         input.Email,
			DisplayName:   input.DisplayName,
			IsAdmin:       input.IsAdmin,
			Disabled:      input.Disabled,
			Locale:        input.Locale,
			EmailVerified: input.EmailVerified,
		})

	start := time.Now()
	resp, err := c.raw.Users.PutAPIUsersIDContext(ctx, params)
	recordCall("update_user", err, time.Since(start))
	if err != nil {
		return nil, fmt.Errorf("update user failed: %w", err)
	}

	return userFromDTO(resp.Payload), nil
}

// UpdateUserCustomClaims replaces the full set of custom claims on a user.
func (c *Client) UpdateUserCustomClaims(ctx context.Context, id string, claims []CustomClaim) ([]CustomClaim, error) {
	params := custom_claims.NewPutAPICustomClaimsUserUserIDParams().
		WithUserID(id).
		WithClaims(customClaimsToDTO(claims))

	start := time.Now()
	resp, err := c.raw.CustomClaims.PutAPICustomClaimsUserUserIDContext(ctx, params)
	recordCall("update_user_custom_claims", err, time.Since(start))
	if err != nil {
		return nil, fmt.Errorf("update user custom claims failed: %w", err)
	}

	return customClaimsFromDTO(resp.Payload), nil
}

func (c *Client) DeleteUser(ctx context.Context, id string) error {
	params := users.NewDeleteAPIUsersIDParams().
		WithID(id)

	start := time.Now()
	_, err := c.raw.Users.DeleteAPIUsersIDContext(ctx, params)
	recordCall("delete_user", err, time.Since(start))
	if err != nil {
		return fmt.Errorf("delete user failed: %w", err)
	}

	return nil
}

// --- API Key Operations ---

// CreateAPIKeyForUser creates an API key for the specified user by exchanging a one-time access token for a session.
func (c *Client) CreateAPIKeyForUser(ctx context.Context, userID, name, expiresAt, description string, tokenTTLMinutes int) (result *APIKeyWithToken, err error) {
	start := time.Now()
	defer func() { recordCall("create_api_key_for_user", err, time.Since(start)) }()

	token, err := c.CreateOneTimeAccessToken(ctx, userID, tokenTTLMinutes)
	if err != nil {
		return nil, fmt.Errorf("create one-time access token: %w", err)
	}

	session := newSessionClient(c.baseURL, c.httpClient)
	cookies, err := session.exchangeOneTimeAccessToken(ctx, token.Token)
	if err != nil {
		return nil, fmt.Errorf("exchange one-time access token: %w", err)
	}

	apiKeyReq := CreateAPIKeyRequest{
		Name:        name,
		ExpiresAt:   expiresAt,
		Description: description,
	}
	apiKeyResp, err := session.createAPIKeyWithCookies(ctx, cookies, apiKeyReq)
	if err != nil {
		return nil, fmt.Errorf("create API key: %w", err)
	}

	return &APIKeyWithToken{
		APIKey: apiKeyFromCreateResponse(apiKeyResp),
		Token:  apiKeyResp.Token,
	}, nil
}

// DeleteAPIKey deletes an API key by ID.
func (c *Client) DeleteAPIKey(ctx context.Context, id string) error {
	params := api_keys.NewDeleteAPIAPIKeysIDParams().
		WithID(id)

	start := time.Now()
	_, err := c.raw.APIKeys.DeleteAPIAPIKeysIDContext(ctx, params)
	recordCall("delete_api_key", err, time.Since(start))
	if err != nil {
		return fmt.Errorf("delete API key failed: %w", err)
	}

	return nil
}

// --- OIDC Client Operations ---

// ListOIDCClients returns a list of OIDC clients matching the search term.
// If search is empty, all OIDC clients are returned.
func (c *Client) ListOIDCClients(ctx context.Context, search string) ([]*OIDCClient, error) {
	params := oidc.NewGetAPIOidcClientsParams()

	if search != "" {
		params = params.WithSearch(&search)
	}

	start := time.Now()
	resp, err := c.raw.OIDc.GetAPIOidcClientsContext(ctx, params)
	recordCall("list_oidc_clients", err, time.Since(start))
	if err != nil {
		return nil, fmt.Errorf("list OIDC clients failed: %w", err)
	}

	clientList := make([]*OIDCClient, 0, len(resp.Payload.Data))
	for _, dto := range resp.Payload.Data {
		clientList = append(clientList, oidcClientFromListDTO(dto))
	}

	return clientList, nil
}

func (c *Client) CreateOIDCClient(ctx context.Context, input OIDCClientInput) (*OIDCClient, error) {
	dto := &models.GithubComPocketIDPocketIDBackendInternalDtoOidcClientCreateDto{
		Name:                                &input.Name,
		Description:                         input.Description,
		CallbackURLs:                        input.CallbackURLs,
		LogoutCallbackURLs:                  input.LogoutCallbackURLs,
		LaunchURL:                           input.LaunchURL,
		LogoURL:                             input.LogoURL,
		DarkLogoURL:                         input.DarkLogoURL,
		HasLogo:                             input.HasLogo,
		HasDarkLogo:                         input.HasDarkLogo,
		IsPublic:                            input.IsPublic,
		IsGroupRestricted:                   input.IsGroupRestricted,
		PkceEnabled:                         input.PKCEEnabled,
		RequiresReauthentication:            input.RequiresReauthentication,
		RequiresPushedAuthorizationRequests: input.RequiresPushedAuthorizationRequests,
		SkipConsent:                         input.SkipConsent,
		AccessTokenDurationMinutes:          input.AccessTokenDurationMinutes,
		RefreshTokenDurationMinutes:         input.RefreshTokenDurationMinutes,
		Credentials:                         oidcCredentialsToDTO(input.Credentials),
	}

	// Only set ID if explicitly provided; otherwise let Pocket-ID autogenerate
	if input.ID != nil {
		dto.ID = *input.ID
	}

	params := oidc.NewPostAPIOidcClientsParams().
		WithClient(dto)

	start := time.Now()
	resp, err := c.raw.OIDc.PostAPIOidcClientsContext(ctx, params)
	recordCall("create_oidc_client", err, time.Since(start))
	if err != nil {
		return nil, fmt.Errorf("create OIDC client failed: %w", err)
	}

	return oidcClientFromAllowedGroupsDTO(resp.Payload), nil
}

func (c *Client) UpdateOIDCClient(ctx context.Context, id string, input OIDCClientInput) (*OIDCClient, error) {
	params := oidc.NewPutAPIOidcClientsIDParams().
		WithID(clientIDPathParam(id)).
		WithClient(&models.GithubComPocketIDPocketIDBackendInternalDtoOidcClientUpdateDto{
			Name:                                &input.Name,
			Description:                         input.Description,
			CallbackURLs:                        input.CallbackURLs,
			LogoutCallbackURLs:                  input.LogoutCallbackURLs,
			LaunchURL:                           input.LaunchURL,
			LogoURL:                             input.LogoURL,
			DarkLogoURL:                         input.DarkLogoURL,
			HasLogo:                             input.HasLogo,
			HasDarkLogo:                         input.HasDarkLogo,
			IsPublic:                            input.IsPublic,
			IsGroupRestricted:                   input.IsGroupRestricted,
			PkceEnabled:                         input.PKCEEnabled,
			RequiresReauthentication:            input.RequiresReauthentication,
			RequiresPushedAuthorizationRequests: input.RequiresPushedAuthorizationRequests,
			SkipConsent:                         input.SkipConsent,
			AccessTokenDurationMinutes:          input.AccessTokenDurationMinutes,
			RefreshTokenDurationMinutes:         input.RefreshTokenDurationMinutes,
			Credentials:                         oidcCredentialsToDTO(input.Credentials),
		})

	start := time.Now()
	resp, err := c.raw.OIDc.PutAPIOidcClientsIDContext(ctx, params)
	recordCall("update_oidc_client", err, time.Since(start))
	if err != nil {
		return nil, fmt.Errorf("update OIDC client failed: %w", err)
	}

	return oidcClientFromAllowedGroupsDTO(resp.Payload), nil
}

func (c *Client) GetOIDCClient(ctx context.Context, id string) (*OIDCClient, error) {
	params := oidc.NewGetAPIOidcClientsIDParams().
		WithID(clientIDPathParam(id))

	start := time.Now()
	resp, err := c.raw.OIDc.GetAPIOidcClientsIDContext(ctx, params)
	recordCall("get_oidc_client", err, time.Since(start))
	if err != nil {
		return nil, fmt.Errorf("get OIDC client failed: %w", err)
	}

	return oidcClientFromAllowedGroupsDTO(resp.Payload), nil
}

// RefreshOIDCClientMetadata forces a re-fetch of a CIMD client's metadata document,
// bypassing the cache TTL. Pocket-ID rejects the call for standard clients and when no
// CIMD allowlist is configured. The refreshed client is discarded: the reconcile that
// triggers this re-reads the canonical state immediately afterwards.
func (c *Client) RefreshOIDCClientMetadata(ctx context.Context, id string) error {
	params := oidc.NewPostAPIOidcClientsIDRefreshParams().
		WithID(clientIDPathParam(id))

	start := time.Now()
	_, err := c.raw.OIDc.PostAPIOidcClientsIDRefreshContext(ctx, params)
	recordCall("refresh_oidc_client_metadata", err, time.Since(start))
	if err != nil {
		return fmt.Errorf("refresh OIDC client metadata failed: %w", err)
	}

	return nil
}

func (c *Client) DeleteOIDCClient(ctx context.Context, id string) error {
	params := oidc.NewDeleteAPIOidcClientsIDParams().
		WithID(clientIDPathParam(id))

	start := time.Now()
	_, err := c.raw.OIDc.DeleteAPIOidcClientsIDContext(ctx, params)
	recordCall("delete_oidc_client", err, time.Since(start))
	if err != nil {
		return fmt.Errorf("delete OIDC client failed: %w", err)
	}

	return nil
}

func (c *Client) UpdateOIDCClientAllowedGroups(ctx context.Context, id string, groupIDs []string) error {
	// Retry on 500 errors as it's usually transient
	retryDelays := []time.Duration{150 * time.Millisecond, 350 * time.Millisecond}
	var lastErr error
	for attempt := 0; attempt <= len(retryDelays); attempt++ {
		if attempt > 0 {
			select {
			case <-ctx.Done():
				return ctx.Err()
			case <-time.After(retryDelays[attempt-1]):
			}
		}
		params := oidc.NewPutAPIOidcClientsIDAllowedUserGroupsParams().
			WithID(clientIDPathParam(id)).
			WithGroups(&models.GithubComPocketIDPocketIDBackendInternalDtoOidcUpdateAllowedUserGroupsDto{
				UserGroupIds: groupIDs,
			})
		start := time.Now()
		_, callErr := c.raw.OIDc.PutAPIOidcClientsIDAllowedUserGroupsContext(ctx, params)
		recordCall("update_oidc_client_allowed_groups", callErr, time.Since(start))
		if callErr != nil {
			if IsServerError(callErr) {
				lastErr = fmt.Errorf("update OIDC client allowed groups failed: %w", callErr)
				continue
			}
			return fmt.Errorf("update OIDC client allowed groups failed: %w", callErr)
		}
		return nil
	}
	return lastErr
}

// CreateOIDCClientSecret adds a secret and returns it alongside its value; an empty secret lets
// Pocket-ID generate one. Existing secrets stay valid, so the caller decides when to retire them.
// The value is only disclosed here — a dropped response leaves a secret that exists but is
// unusable, deletable only by its ID.
func (c *Client) CreateOIDCClientSecret(ctx context.Context, id, secret string) (OIDCClientSecret, string, error) {
	params := oidc.NewPostAPIOidcClientsIDSecretsParams().
		WithID(clientIDPathParam(id)).
		WithPayload(&models.GithubComPocketIDPocketIDBackendInternalDtoOidcClientSecretCreateDto{Secret: secret})

	start := time.Now()
	resp, err := c.raw.OIDc.PostAPIOidcClientsIDSecretsContext(ctx, params)
	recordCall("create_oidc_client_secret", err, time.Since(start))
	if err != nil {
		return OIDCClientSecret{}, "", fmt.Errorf("create OIDC client secret failed: %w", err)
	}
	// The generated reader always allocates Payload and tolerates an empty body, so an unusable
	// response shows up as a missing value rather than a nil payload.
	if resp.Payload.Secret == "" {
		return OIDCClientSecret{}, "", fmt.Errorf("create OIDC client secret returned no secret value")
	}

	return oidcClientSecretFromCreatedDTO(resp.Payload), resp.Payload.Secret, nil
}

// DeleteOIDCClientSecret makes a secret immediately unusable. One already gone counts as deleted,
// so a retried retirement converges.
func (c *Client) DeleteOIDCClientSecret(ctx context.Context, id, secretID string) error {
	params := oidc.NewDeleteAPIOidcClientsIDSecretsSecretIDParams().
		WithID(clientIDPathParam(id)).
		WithSecretID(secretID)

	start := time.Now()
	_, err := c.raw.OIDc.DeleteAPIOidcClientsIDSecretsSecretIDContext(ctx, params)
	recordCall("delete_oidc_client_secret", err, time.Since(start))
	if err != nil && !IsNotFoundError(err) {
		return fmt.Errorf("delete OIDC client secret failed: %w", err)
	}

	return nil
}

// --- SCIM Service Provider Operations ---

// GetOIDCClientSCIMServiceProvider fetches the SCIM service provider configured for an OIDC client.
// Returns nil, nil if no SCIM service provider is configured (404).
func (c *Client) GetOIDCClientSCIMServiceProvider(ctx context.Context, oidcClientID string) (*SCIMServiceProvider, error) {
	params := oidc.NewGetAPIOidcClientsIDScimServiceProviderParams().
		WithID(clientIDPathParam(oidcClientID))

	start := time.Now()
	resp, err := c.raw.OIDc.GetAPIOidcClientsIDScimServiceProviderContext(ctx, params)
	recordCall("get_oidc_client_scim_service_provider", err, time.Since(start))
	if err != nil {
		if IsNotFoundError(err) {
			return nil, nil
		}
		return nil, fmt.Errorf("get OIDC client SCIM service provider failed: %w", err)
	}

	return scimFromDTO(resp.Payload), nil
}

// CreateSCIMServiceProvider creates a new SCIM service provider.
func (c *Client) CreateSCIMServiceProvider(ctx context.Context, input SCIMServiceProviderInput) (*SCIMServiceProvider, error) {
	params := scim.NewPostAPIScimServiceProviderParams().
		WithServiceProvider(&models.ScimsyncScimServiceProviderCreateDTO{
			Endpoint:     &input.Endpoint,
			OidcClientID: &input.OIDCClientID,
			Token:        input.Token,
		})

	start := time.Now()
	resp, err := c.raw.Scim.PostAPIScimServiceProviderContext(ctx, params)
	recordCall("create_scim_service_provider", err, time.Since(start))
	if err != nil {
		return nil, fmt.Errorf("create SCIM service provider failed: %w", err)
	}

	return scimFromDTO(resp.Payload), nil
}

// UpdateSCIMServiceProvider updates an existing SCIM service provider.
func (c *Client) UpdateSCIMServiceProvider(ctx context.Context, id string, input SCIMServiceProviderInput) (*SCIMServiceProvider, error) {
	params := scim.NewPutAPIScimServiceProviderIDParams().
		WithID(id).
		WithServiceProvider(&models.ScimsyncScimServiceProviderCreateDTO{
			Endpoint:     &input.Endpoint,
			OidcClientID: &input.OIDCClientID,
			Token:        input.Token,
		})

	start := time.Now()
	resp, err := c.raw.Scim.PutAPIScimServiceProviderIDContext(ctx, params)
	recordCall("update_scim_service_provider", err, time.Since(start))
	if err != nil {
		return nil, fmt.Errorf("update SCIM service provider failed: %w", err)
	}

	return scimFromDTO(resp.Payload), nil
}

// DeleteSCIMServiceProvider deletes a SCIM service provider by its pocket-id ID.
func (c *Client) DeleteSCIMServiceProvider(ctx context.Context, id string) error {
	params := scim.NewDeleteAPIScimServiceProviderIDParams().
		WithID(id)

	start := time.Now()
	_, err := c.raw.Scim.DeleteAPIScimServiceProviderIDContext(ctx, params)
	recordCall("delete_scim_service_provider", err, time.Since(start))
	if err != nil {
		return fmt.Errorf("delete SCIM service provider failed: %w", err)
	}

	return nil
}

// --- API Operations ---

// API represents a Pocket-ID API (a protected resource / token audience).
type API struct {
	ID               string
	Name             string
	Resource         string
	CreatedAt        string
	AllowCIMDClients bool
	Permissions      []APIPermission
}

// APIPermission represents a scoped permission offered by an API.
type APIPermission struct {
	ID                    string
	Key                   string
	Name                  string
	Description           string
	AllowedForCIMDClients bool
}

// APIInput contains the fields for creating an API.
type APIInput struct {
	Name     string
	Resource string
}

// APIPermissionInput contains the fields for creating or updating an API permission.
type APIPermissionInput struct {
	Key         string
	Name        string
	Description string
}

// APIClientGrant represents an OIDC client's access to a single API, split by the flow
// it applies to. Access granted through an API's CIMD setting is owned by the API and is
// not represented here.
type APIClientGrant struct {
	APIID    string
	Resource string
	// CIMDGranted reports access the API grants to every CIMD client. It is owned by the
	// API, not the client, so it is reported but never reconciled from this side.
	CIMDGranted                bool
	ClientAccess               bool
	UserDelegatedAccess        bool
	ClientPermissionIDs        []string
	UserDelegatedPermissionIDs []string
}

// IsEmpty reports whether the grant conveys no access at all.
func (g APIClientGrant) IsEmpty() bool {
	return !g.ClientAccess && !g.UserDelegatedAccess &&
		len(g.ClientPermissionIDs) == 0 && len(g.UserDelegatedPermissionIDs) == 0
}

// ListAPIs returns a list of APIs matching the search term (matched against name
// or resource). If search is empty, all APIs are returned.
func (c *Client) ListAPIs(ctx context.Context, search string) ([]*API, error) {
	params := apis.NewGetAPIApisParams()
	if search != "" {
		params = params.WithSearch(&search)
	}

	start := time.Now()
	resp, err := c.raw.Apis.GetAPIApisContext(ctx, params)
	recordCall("list_apis", err, time.Since(start))
	if err != nil {
		return nil, fmt.Errorf("list APIs failed: %w", err)
	}

	apiList := make([]*API, 0, len(resp.Payload.Data))
	for _, dto := range resp.Payload.Data {
		apiList = append(apiList, apiFromDTO(dto))
	}
	return apiList, nil
}

// GetAPI returns a single API by ID, including its permissions.
func (c *Client) GetAPI(ctx context.Context, id string) (*API, error) {
	params := apis.NewGetAPIApisIDParams().WithID(id)

	start := time.Now()
	resp, err := c.raw.Apis.GetAPIApisIDContext(ctx, params)
	recordCall("get_api", err, time.Since(start))
	if err != nil {
		return nil, fmt.Errorf("get API failed: %w", err)
	}
	return apiFromDTO(resp.Payload), nil
}

// CreateAPI creates a new API with the given name and resource.
func (c *Client) CreateAPI(ctx context.Context, input APIInput) (*API, error) {
	params := apis.NewPostAPIApisParams().
		WithAPI(&models.APIAPICreateDto{
			Name:     &input.Name,
			Resource: &input.Resource,
		})

	start := time.Now()
	resp, err := c.raw.Apis.PostAPIApisContext(ctx, params)
	recordCall("create_api", err, time.Since(start))
	if err != nil {
		return nil, fmt.Errorf("create API failed: %w", err)
	}
	return apiFromDTO(resp.Payload), nil
}

// UpdateAPI updates an API's name. The resource is immutable in Pocket-ID.
func (c *Client) UpdateAPI(ctx context.Context, id, name string) (*API, error) {
	params := apis.NewPutAPIApisIDParams().
		WithID(id).
		WithAPI(&models.APIAPIUpdateDto{Name: &name})

	start := time.Now()
	resp, err := c.raw.Apis.PutAPIApisIDContext(ctx, params)
	recordCall("update_api", err, time.Since(start))
	if err != nil {
		return nil, fmt.Errorf("update API failed: %w", err)
	}
	return apiFromDTO(resp.Payload), nil
}

// DeleteAPI deletes an API by ID.
func (c *Client) DeleteAPI(ctx context.Context, id string) error {
	params := apis.NewDeleteAPIApisIDParams().WithID(id)

	start := time.Now()
	_, err := c.raw.Apis.DeleteAPIApisIDContext(ctx, params)
	recordCall("delete_api", err, time.Since(start))
	if err != nil {
		return fmt.Errorf("delete API failed: %w", err)
	}
	return nil
}

// UpdateAPIPermissions replaces the full permission set for an API and returns
// the updated API (permissions with their assigned IDs).
func (c *Client) UpdateAPIPermissions(ctx context.Context, id string, permissions []APIPermissionInput) (*API, error) {
	payload := make([]*models.APIAPIPermissionInputDto, 0, len(permissions))
	for i := range permissions {
		p := permissions[i]
		payload = append(payload, &models.APIAPIPermissionInputDto{
			Key:         &p.Key,
			Name:        &p.Name,
			Description: p.Description,
		})
	}

	params := apis.NewPutAPIApisIDPermissionsParams().
		WithID(id).
		WithPermissions(&models.APIAPIPermissionsUpdateDto{Permissions: payload})

	start := time.Now()
	resp, err := c.raw.Apis.PutAPIApisIDPermissionsContext(ctx, params)
	recordCall("update_api_permissions", err, time.Since(start))
	if err != nil {
		return nil, fmt.Errorf("update API permissions failed: %w", err)
	}
	return apiFromDTO(resp.Payload), nil
}

// SetAPICIMDAccess replaces which permissions of an API every client registered through a
// Client ID Metadata Document may request. Pocket-ID retains the permission IDs while
// enabled is false, so switching access off and back on preserves the selection.
func (c *Client) SetAPICIMDAccess(ctx context.Context, apiID string, enabled bool, permissionIDs []string) (*API, error) {
	if permissionIDs == nil {
		permissionIDs = []string{}
	}
	params := apis.NewPutAPIApisIDCimdAccessParams().
		WithID(apiID).
		WithAccess(&models.APIAPICimdAccessUpdateDto{
			Enabled:       enabled,
			PermissionIds: permissionIDs,
		})

	start := time.Now()
	resp, err := c.raw.Apis.PutAPIApisIDCimdAccessContext(ctx, params)
	recordCall("set_api_cimd_access", err, time.Since(start))
	if err != nil {
		return nil, fmt.Errorf("set API CIMD access failed: %w", err)
	}
	return apiFromDTO(resp.Payload), nil
}

// ListAPIClientGrants returns the client's grant on every API it may reach. An entry whose
// grant IsEmpty is reachable only through the API's CIMD setting.
func (c *Client) ListAPIClientGrants(ctx context.Context, clientID string) ([]APIClientGrant, error) {
	params := apis.NewGetAPIAPIAccessClientIDApisParams().WithClientID(clientIDPathParam(clientID))

	start := time.Now()
	resp, err := c.raw.Apis.GetAPIAPIAccessClientIDApisContext(ctx, params)
	recordCall("list_api_client_grants", err, time.Since(start))
	if err != nil {
		return nil, fmt.Errorf("list API client grants failed: %w", err)
	}

	grants := make([]APIClientGrant, 0, len(resp.Payload))
	for _, dto := range resp.Payload {
		if dto == nil || dto.API == nil {
			continue
		}
		grants = append(grants, APIClientGrant{
			APIID:                      dto.API.ID,
			Resource:                   dto.API.Resource,
			CIMDGranted:                dto.CimdGrantedAccess || len(dto.CimdGrantedPermissionIds) > 0,
			ClientAccess:               dto.ClientAccess,
			UserDelegatedAccess:        dto.UserDelegatedAccess,
			ClientPermissionIDs:        dto.ClientPermissionIds,
			UserDelegatedPermissionIDs: dto.UserDelegatedPermissionIds,
		})
	}
	return grants, nil
}

// SetAPIClientGrant replaces the client's grant on a single API and returns the grant
// Pocket-ID applied, which may be narrower than requested: unknown permission IDs are
// dropped, and a public client never keeps client-credentials access.
func (c *Client) SetAPIClientGrant(ctx context.Context, apiID, clientID string, grant APIClientGrant) (*APIClientGrant, error) {
	params := apis.NewPutAPIApisIDClientsClientIDParams().
		WithID(apiID).
		WithClientID(clientIDPathParam(clientID)).
		WithAccess(&models.APIAPIClientGrantUpdateDto{
			ClientAccess:               grant.ClientAccess,
			UserDelegatedAccess:        grant.UserDelegatedAccess,
			ClientPermissionIds:        grant.ClientPermissionIDs,
			UserDelegatedPermissionIds: grant.UserDelegatedPermissionIDs,
		})

	start := time.Now()
	resp, err := c.raw.Apis.PutAPIApisIDClientsClientIDContext(ctx, params)
	recordCall("set_api_client_grant", err, time.Since(start))
	if err != nil {
		return nil, fmt.Errorf("set API client grant failed: %w", err)
	}
	return &APIClientGrant{
		APIID:                      apiID,
		ClientAccess:               resp.Payload.ClientAccess,
		UserDelegatedAccess:        resp.Payload.UserDelegatedAccess,
		ClientPermissionIDs:        resp.Payload.ClientPermissionIds,
		UserDelegatedPermissionIDs: resp.Payload.UserDelegatedPermissionIds,
	}, nil
}

// RemoveAPIClientGrant revokes every grant the client holds on one API. A grant that is
// already gone is treated as removed.
func (c *Client) RemoveAPIClientGrant(ctx context.Context, apiID, clientID string) error {
	params := apis.NewDeleteAPIApisIDClientsClientIDParams().
		WithID(apiID).
		WithClientID(clientIDPathParam(clientID))

	start := time.Now()
	_, err := c.raw.Apis.DeleteAPIApisIDClientsClientIDContext(ctx, params)
	recordCall("remove_api_client_grant", err, time.Since(start))
	if err != nil && !IsNotFoundError(err) {
		return fmt.Errorf("remove API client grant failed: %w", err)
	}
	return nil
}

// --- User Group Operations ---

// ListUserGroups returns a list of user groups matching the search term.
// If search is empty, all user groups are returned.
func (c *Client) ListUserGroups(ctx context.Context, search string) ([]*UserGroup, error) {
	params := user_groups.NewGetAPIUserGroupsParams()

	if search != "" {
		params = params.WithSearch(&search)
	}

	start := time.Now()
	resp, err := c.raw.UserGroups.GetAPIUserGroupsContext(ctx, params)
	recordCall("list_user_groups", err, time.Since(start))
	if err != nil {
		return nil, fmt.Errorf("list user groups failed: %w", err)
	}

	groupList := make([]*UserGroup, 0, len(resp.Payload.Data))
	for _, dto := range resp.Payload.Data {
		groupList = append(groupList, userGroupFromMinimalDTO(dto))
	}

	return groupList, nil
}

func (c *Client) CreateUserGroup(ctx context.Context, name, friendlyName string) (*UserGroup, error) {
	params := user_groups.NewPostAPIUserGroupsParams().
		WithUserGroup(&models.GithubComPocketIDPocketIDBackendInternalDtoUserGroupCreateDto{
			Name:         &name,
			FriendlyName: &friendlyName,
		})

	start := time.Now()
	resp, err := c.raw.UserGroups.PostAPIUserGroupsContext(ctx, params)
	recordCall("create_user_group", err, time.Since(start))
	if err != nil {
		return nil, fmt.Errorf("create user group failed: %w", err)
	}

	return userGroupFromDTO(resp.Payload), nil
}

func (c *Client) UpdateUserGroup(ctx context.Context, id, name, friendlyName string) (*UserGroup, error) {
	params := user_groups.NewPutAPIUserGroupsIDParams().
		WithID(id).
		WithUserGroup(&models.GithubComPocketIDPocketIDBackendInternalDtoUserGroupCreateDto{
			Name:         &name,
			FriendlyName: &friendlyName,
		})

	start := time.Now()
	resp, err := c.raw.UserGroups.PutAPIUserGroupsIDContext(ctx, params)
	recordCall("update_user_group", err, time.Since(start))
	if err != nil {
		return nil, fmt.Errorf("update user group failed: %w", err)
	}

	return userGroupFromDTO(resp.Payload), nil
}

func (c *Client) GetUserGroup(ctx context.Context, id string) (*UserGroup, error) {
	params := user_groups.NewGetAPIUserGroupsIDParams().
		WithID(id)

	start := time.Now()
	resp, err := c.raw.UserGroups.GetAPIUserGroupsIDContext(ctx, params)
	recordCall("get_user_group", err, time.Since(start))
	if err != nil {
		return nil, fmt.Errorf("get user group failed: %w", err)
	}

	return userGroupFromDTO(resp.Payload), nil
}

func (c *Client) DeleteUserGroup(ctx context.Context, id string) error {
	params := user_groups.NewDeleteAPIUserGroupsIDParams().
		WithID(id)

	start := time.Now()
	_, err := c.raw.UserGroups.DeleteAPIUserGroupsIDContext(ctx, params)
	recordCall("delete_user_group", err, time.Since(start))
	if err != nil {
		return fmt.Errorf("delete user group failed: %w", err)
	}

	return nil
}

func (c *Client) UpdateUserGroupUsers(ctx context.Context, id string, userIDs []string) error {
	params := user_groups.NewPutAPIUserGroupsIDUsersParams().
		WithID(id).
		WithUsers(&models.GithubComPocketIDPocketIDBackendInternalDtoUserGroupUpdateUsersDto{
			UserIds: userIDs,
		})

	start := time.Now()
	_, err := c.raw.UserGroups.PutAPIUserGroupsIDUsersContext(ctx, params)
	recordCall("update_user_group_users", err, time.Since(start))
	if err != nil {
		return fmt.Errorf("update user group users failed: %w", err)
	}

	return nil
}

// UpdateUserGroupCustomClaims replaces the full set of custom claims on a user group.
func (c *Client) UpdateUserGroupCustomClaims(ctx context.Context, id string, claims []CustomClaim) ([]CustomClaim, error) {
	params := custom_claims.NewPutAPICustomClaimsUserGroupUserGroupIDParams().
		WithUserGroupID(id).
		WithClaims(customClaimsToDTO(claims))

	start := time.Now()
	resp, err := c.raw.CustomClaims.PutAPICustomClaimsUserGroupUserGroupIDContext(ctx, params)
	recordCall("update_user_group_custom_claims", err, time.Since(start))
	if err != nil {
		return nil, fmt.Errorf("update user group custom claims failed: %w", err)
	}

	return customClaimsFromDTO(resp.Payload), nil
}

// --- One-Time Access Token Operations ---

// OneTimeAccessToken represents a one-time login token.
type OneTimeAccessToken struct {
	Token string
}

// CreateOneTimeAccessToken creates a one-time access token for a user.
// This token can be used to log in via the browser at /lc/{token}
func (c *Client) CreateOneTimeAccessToken(ctx context.Context, userID string, expiresInMinutes int) (*OneTimeAccessToken, error) {
	params := users.NewPostAPIUsersIDOneTimeAccessTokenParams().
		WithID(userID).
		WithBody(map[string]any{
			"userId": userID,
			"ttl":    fmt.Sprintf("%dm", expiresInMinutes),
		})

	start := time.Now()
	resp, err := c.raw.Users.PostAPIUsersIDOneTimeAccessTokenContext(ctx, params)
	recordCall("create_one_time_access_token", err, time.Since(start))
	if err != nil {
		return nil, fmt.Errorf("create one-time access token failed: %w", err)
	}

	// The response payload is `any` type, so we need to type assert
	payload, ok := resp.Payload.(map[string]any)
	if !ok {
		return nil, fmt.Errorf("unexpected response format")
	}

	token, ok := payload["token"].(string)
	if !ok {
		return nil, fmt.Errorf("token not found in response")
	}

	return &OneTimeAccessToken{Token: token}, nil
}

// --- Helpers ---

// DefaultAPIKeyExpiry returns a default expiry time of 1 year from now for API keys.
func DefaultAPIKeyExpiry() time.Time {
	return time.Now().AddDate(1, 0, 0)
}

func userFromDTO(dto *models.GithubComPocketIDPocketIDBackendInternalDtoUserDto) *User {
	if dto == nil {
		return nil
	}
	return &User{
		ID:            dto.ID,
		Username:      dto.Username,
		FirstName:     dto.FirstName,
		LastName:      dto.LastName,
		Email:         dto.Email,
		DisplayName:   dto.DisplayName,
		IsAdmin:       dto.IsAdmin,
		Disabled:      dto.Disabled,
		Locale:        dto.Locale,
		EmailVerified: dto.EmailVerified,
		CustomClaims:  customClaimsFromDTO(dto.CustomClaims),
	}
}

func apiKeyFromCreateResponse(resp *CreateAPIKeyResponse) APIKey {
	if resp == nil {
		return APIKey{}
	}
	return APIKey{
		ID:          resp.APIKey.ID,
		Name:        resp.APIKey.Name,
		Description: resp.APIKey.Description,
		CreatedAt:   resp.APIKey.CreatedAt,
		ExpiresAt:   resp.APIKey.ExpiresAt,
	}
}

func oidcCredentialsToDTO(credentials *OIDCClientCredentials) *models.GithubComPocketIDPocketIDBackendInternalDtoOidcClientCredentialsDto {
	if credentials == nil {
		return nil
	}
	identities := make([]*models.GithubComPocketIDPocketIDBackendInternalDtoOidcClientFederatedIdentityDto, 0, len(credentials.FederatedIdentities))
	for _, identity := range credentials.FederatedIdentities {
		identities = append(identities, &models.GithubComPocketIDPocketIDBackendInternalDtoOidcClientFederatedIdentityDto{
			Issuer:           identity.Issuer,
			Subject:          identity.Subject,
			Audience:         identity.Audience,
			Jwks:             identity.JWKS,
			ReplayProtection: identity.ReplayProtection,
		})
	}
	return &models.GithubComPocketIDPocketIDBackendInternalDtoOidcClientCredentialsDto{
		FederatedIdentities: identities,
	}
}

func oidcClientSecretsFromCredentialsDTO(dto *models.GithubComPocketIDPocketIDBackendInternalDtoOidcClientCredentialsDto) []OIDCClientSecret {
	if dto == nil {
		return nil
	}
	return oidcClientSecretsFromDTO(dto.Secrets)
}

func oidcClientSecretsFromDTO(dtos []*models.GithubComPocketIDPocketIDBackendInternalDtoOidcClientSecretDto) []OIDCClientSecret {
	secrets := make([]OIDCClientSecret, 0, len(dtos))
	for _, dto := range dtos {
		if dto == nil || dto.ID == "" {
			continue
		}
		secrets = append(secrets, OIDCClientSecret{
			ID:        dto.ID,
			Prefix:    dto.Prefix,
			CreatedAt: parseAPITime(dto.CreatedAt),
			IsActive:  dto.IsActive,
		})
	}
	return secrets
}

func oidcClientSecretFromCreatedDTO(dto *models.GithubComPocketIDPocketIDBackendInternalDtoOidcClientSecretCreatedDto) OIDCClientSecret {
	return OIDCClientSecret{
		ID:        dto.ID,
		Prefix:    dto.Prefix,
		CreatedAt: parseAPITime(dto.CreatedAt),
		IsActive:  dto.IsActive,
	}
}

// parseAPITime reads one of Pocket-ID's RFC 3339 timestamps, typed as a plain string by the
// generated models. An unparseable value yields the zero time, meaning "unknown".
func parseAPITime(value string) time.Time {
	if value == "" {
		return time.Time{}
	}
	parsed, err := time.Parse(time.RFC3339, value)
	if err != nil {
		return time.Time{}
	}
	return parsed
}

func oidcClientFromListDTO(dto *models.GithubComPocketIDPocketIDBackendInternalDtoOidcClientWithAllowedGroupsCountDto) *OIDCClient {
	if dto == nil {
		return nil
	}
	return &OIDCClient{
		ID:                                  dto.ID,
		Name:                                dto.Name,
		Description:                         dto.Description,
		CallbackURLs:                        dto.CallbackURLs,
		LogoutCallbackURLs:                  dto.LogoutCallbackURLs,
		LaunchURL:                           dto.LaunchURL,
		HasLogo:                             dto.HasLogo,
		HasDarkLogo:                         dto.HasDarkLogo,
		IsPublic:                            dto.IsPublic,
		IsGroupRestricted:                   dto.IsGroupRestricted,
		PKCEEnabled:                         dto.PkceEnabled,
		PKCESupported:                       dto.PkceSupported,
		RequiresReauthentication:            dto.RequiresReauthentication,
		RequiresPushedAuthorizationRequests: dto.RequiresPushedAuthorizationRequests,
		SkipConsent:                         dto.SkipConsent,
		AccessTokenDurationMinutes:          dto.AccessTokenDurationMinutes,
		RefreshTokenDurationMinutes:         dto.RefreshTokenDurationMinutes,
		AllowedUserGroupIDs:                 []string{},
		ClientType:                          dto.ClientType,
		Secrets:                             oidcClientSecretsFromCredentialsDTO(dto.Credentials),
	}
}

func oidcClientFromAllowedGroupsDTO(dto *models.GithubComPocketIDPocketIDBackendInternalDtoOidcClientWithAllowedUserGroupsDto) *OIDCClient {
	if dto == nil {
		return nil
	}
	groupIDs := make([]string, 0, len(dto.AllowedUserGroups))
	for _, group := range dto.AllowedUserGroups {
		if group == nil || group.ID == "" {
			continue
		}
		groupIDs = append(groupIDs, group.ID)
	}
	return &OIDCClient{
		ID:                                  dto.ID,
		Name:                                dto.Name,
		Description:                         dto.Description,
		CallbackURLs:                        dto.CallbackURLs,
		LogoutCallbackURLs:                  dto.LogoutCallbackURLs,
		LaunchURL:                           dto.LaunchURL,
		HasLogo:                             dto.HasLogo,
		HasDarkLogo:                         dto.HasDarkLogo,
		IsPublic:                            dto.IsPublic,
		IsGroupRestricted:                   dto.IsGroupRestricted,
		PKCEEnabled:                         dto.PkceEnabled,
		PKCESupported:                       dto.PkceSupported,
		RequiresReauthentication:            dto.RequiresReauthentication,
		RequiresPushedAuthorizationRequests: dto.RequiresPushedAuthorizationRequests,
		SkipConsent:                         dto.SkipConsent,
		AccessTokenDurationMinutes:          dto.AccessTokenDurationMinutes,
		RefreshTokenDurationMinutes:         dto.RefreshTokenDurationMinutes,
		AllowedUserGroupIDs:                 groupIDs,
		ClientType:                          dto.ClientType,
		Secrets:                             oidcClientSecretsFromCredentialsDTO(dto.Credentials),
	}
}

func userGroupFromMinimalDTO(dto *models.GithubComPocketIDPocketIDBackendInternalDtoUserGroupMinimalDto) *UserGroup {
	if dto == nil {
		return nil
	}
	return &UserGroup{
		ID:           dto.ID,
		Name:         dto.Name,
		FriendlyName: dto.FriendlyName,
		CreatedAt:    dto.CreatedAt,
		LdapID:       dto.LdapID,
		UserCount:    0,   // Minimal DTO doesn't include users
		CustomClaims: nil, // Minimal DTO doesn't include custom claims
	}
}

func userGroupFromDTO(dto *models.GithubComPocketIDPocketIDBackendInternalDtoUserGroupDto) *UserGroup {
	if dto == nil {
		return nil
	}
	userIds := make([]string, 0, len(dto.Users))
	for _, user := range dto.Users {
		if user != nil && user.ID != "" {
			userIds = append(userIds, user.ID)
		}
	}
	clientIDs := make([]string, 0, len(dto.AllowedOidcClients))
	for _, client := range dto.AllowedOidcClients {
		if client != nil && client.ID != "" {
			clientIDs = append(clientIDs, client.ID)
		}
	}
	return &UserGroup{
		ID:                   dto.ID,
		Name:                 dto.Name,
		FriendlyName:         dto.FriendlyName,
		CreatedAt:            dto.CreatedAt,
		LdapID:               dto.LdapID,
		UserCount:            len(dto.Users),
		UserIDs:              userIds,
		CustomClaims:         customClaimsFromDTO(dto.CustomClaims),
		AllowedOIDCClientIDs: clientIDs,
	}
}

func apiFromDTO(dto *models.APIAPIResponseDto) *API {
	if dto == nil {
		return nil
	}
	permissions := make([]APIPermission, 0, len(dto.Permissions))
	for _, p := range dto.Permissions {
		if p == nil {
			continue
		}
		permissions = append(permissions, APIPermission{
			ID:                    p.ID,
			Key:                   p.Key,
			Name:                  p.Name,
			Description:           p.Description,
			AllowedForCIMDClients: p.AllowedForCimdClients,
		})
	}
	return &API{
		ID:               dto.ID,
		Name:             dto.Name,
		Resource:         dto.Resource,
		CreatedAt:        dto.CreatedAt,
		AllowCIMDClients: dto.AllowCimdClients,
		Permissions:      permissions,
	}
}

func scimFromDTO(dto *models.ScimsyncScimServiceProviderDTO) *SCIMServiceProvider {
	if dto == nil {
		return nil
	}
	oidcClientID := ""
	if dto.OidcClient != nil {
		oidcClientID = dto.OidcClient.ID
	}
	return &SCIMServiceProvider{
		ID:           dto.ID,
		Endpoint:     dto.Endpoint,
		Token:        dto.Token,
		OIDCClientID: oidcClientID,
		CreatedAt:    dto.CreatedAt,
		LastSyncedAt: dto.LastSyncedAt,
	}
}

func customClaimsFromDTO(dto []*models.GithubComPocketIDPocketIDBackendInternalDtoCustomClaimDto) []CustomClaim {
	if len(dto) == 0 {
		return nil
	}
	claims := make([]CustomClaim, 0, len(dto))
	for _, claim := range dto {
		if claim == nil {
			continue
		}
		claims = append(claims, CustomClaim{
			Key:   claim.Key,
			Value: claim.Value,
		})
	}
	if len(claims) == 0 {
		return nil
	}
	return claims
}

func customClaimsToDTO(claims []CustomClaim) []*models.GithubComPocketIDPocketIDBackendInternalDtoCustomClaimCreateDto {
	payload := make([]*models.GithubComPocketIDPocketIDBackendInternalDtoCustomClaimCreateDto, 0, len(claims))
	for _, claim := range claims {
		key := claim.Key
		value := claim.Value
		payload = append(payload, &models.GithubComPocketIDPocketIDBackendInternalDtoCustomClaimCreateDto{
			Key:   &key,
			Value: &value,
		})
	}
	return payload
}
