//go:build e2e
// +build e2e

package e2e

import (
	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"
)

var _ = Describe("OIDC Client ID Handling", Ordered, func() {
	// These tests verify the behavior of OIDC client ID handling:
	// 1. When spec.clientID is not set, Pocket-ID autogenerates an ID
	// 2. spec.clientID cannot be added after initial creation with nil

	Context("Autogenerated Client ID", func() {
		const clientName = "test-autogen-clientid"

		It("should use autogenerated client ID from Pocket-ID when spec.clientID is not set", func() {
			By("creating a PocketIDOIDCClient without spec.clientID")
			createOIDCClient(OIDCClientOptions{
				Name:         clientName,
				CallbackURLs: []string{"https://autogen-test.example.com/callback"},
				// Note: ClientID is intentionally not set
			})

			By("waiting for the client to be ready")
			waitForReady("pocketidoidcclient", clientName, userNS)

			By("verifying status.clientID is set and is a valid UUID (not the resource name)")
			statusClientID := waitForStatusFieldNotEmpty("pocketidoidcclient", clientName, userNS, ".status.clientID")

			// The autogenerated ID should NOT be the resource name (old behavior)
			// It should be a UUID generated by Pocket-ID
			Expect(statusClientID).NotTo(Equal(clientName),
				"status.clientID should be autogenerated by Pocket-ID, not inferred from resource name")
			Expect(statusClientID).NotTo(BeEmpty(),
				"status.clientID should be set from Pocket-ID response")

			By("verifying the secret contains the autogenerated client ID")
			secretClientID := waitForSecretKey(clientName+"-oidc-credentials", userNS, "client_id")
			Expect(secretClientID).To(Equal(statusClientID),
				"secret client_id should match status.clientID")
		})

		AfterAll(func() {
			kubectlDelete("pocketidoidcclient", clientName, userNS)
			waitForResourceDeleted("pocketidoidcclient", clientName, userNS)
		})
	})

	Context("Immutable Client ID After Creation", func() {
		const clientName = "test-immutable-clientid"

		It("should not allow adding spec.clientID after resource is created with nil spec.clientID", func() {
			By("creating a PocketIDOIDCClient without spec.clientID")
			createOIDCClient(OIDCClientOptions{
				Name:         clientName,
				CallbackURLs: []string{"https://immutable-test.example.com/callback"},
				// Note: ClientID is intentionally not set
			})

			By("waiting for the client to be ready")
			waitForReady("pocketidoidcclient", clientName, userNS)

			By("capturing the autogenerated client ID from status")
			originalClientID := waitForStatusFieldNotEmpty("pocketidoidcclient", clientName, userNS, ".status.clientID")
			Expect(originalClientID).NotTo(BeEmpty())

			By("attempting to update the resource with a spec.clientID")
			createOIDCClient(OIDCClientOptions{
				Name:         clientName,
				ClientID:     "my-custom-client-id",
				CallbackURLs: []string{"https://immutable-test.example.com/callback"},
			})

			By("verifying the status.clientID remains unchanged (autogenerated ID is preserved)")
			waitForReady("pocketidoidcclient", clientName, userNS)
			currentClientID := kubectlGet("pocketidoidcclient", clientName, "-n", userNS,
				"-o", "jsonpath={.status.clientID}")
			Expect(currentClientID).To(Equal(originalClientID),
				"status.clientID should remain the original autogenerated ID")
		})

		AfterAll(func() {
			kubectlDelete("pocketidoidcclient", clientName, userNS)
			waitForResourceDeleted("pocketidoidcclient", clientName, userNS)
		})
	})
})
