//go:build e2e
// +build e2e

package e2e

import (
	"encoding/json"
	"time"

	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"
)

// pocketIDUser is the subset of Pocket-ID's user payload the ID tests assert on.
type pocketIDUser struct {
	ID          string `json:"id"`
	Username    string `json:"username"`
	FirstName   string `json:"firstName"`
	LastName    string `json:"lastName"`
	Email       string `json:"email"`
	DisplayName string `json:"displayName"`
	IsAdmin     bool   `json:"isAdmin"`
	Disabled    bool   `json:"disabled"`
}

// getUserFromPocketID reads a user straight out of Pocket-ID by ID. getFromPocketID
// requires a 2xx, so a successful decode also proves the ID exists in Pocket-ID.
func getUserFromPocketID(userID string) pocketIDUser {
	body := getFromPocketID("/api/users/" + userID)
	Expect(body).NotTo(BeEmpty(), "Pocket-ID should return a user for ID %s", userID)

	var user pocketIDUser
	Expect(json.Unmarshal([]byte(body), &user)).To(Succeed(), "response body: %s", body)
	return user
}

var _ = Describe("PocketIDUser Declarative User ID", Ordered, func() {
	Context("User created with a declared ID", func() {
		const (
			userName    = "test-declarative-userid"
			declaredID  = "3f8a1c72-9b4d-4e61-8a0f-2c5d7e9b1a34"
			userEmail   = "declared-id@example.com"
			firstName   = "Declared"
			lastName    = "Ident"
			displayName = "Declared Ident"
		)

		BeforeAll(func() {
			createUser(UserOptions{
				Name:        userName,
				UserID:      declaredID,
				Email:       userEmail,
				FirstName:   firstName,
				LastName:    lastName,
				DisplayName: displayName,
			})
			waitForReady("pocketiduser", userName, userNS)
		})

		It("should use the declared ID as status.userID", func() {
			waitForStatusField("pocketiduser", userName, userNS, ".status.userID", declaredID)
		})

		It("should return the user's true state from Pocket-ID for the declared ID", func() {
			user := getUserFromPocketID(declaredID)

			Expect(user.ID).To(Equal(declaredID),
				"Pocket-ID should store the user under the declared ID")
			Expect(user.Username).To(Equal(userName))
			Expect(user.FirstName).To(Equal(firstName))
			Expect(user.LastName).To(Equal(lastName))
			Expect(user.Email).To(Equal(userEmail))
			Expect(user.DisplayName).To(Equal(displayName))
			Expect(user.IsAdmin).To(BeFalse())
			Expect(user.Disabled).To(BeFalse())
		})

		It("should reflect a spec change on the same declared ID", func() {
			By("changing the display name and promoting the user to admin")
			admin := true
			applyYAML(buildUserYAML(UserOptions{
				Name:        userName,
				UserID:      declaredID,
				Email:       userEmail,
				FirstName:   firstName,
				LastName:    lastName,
				DisplayName: "Renamed Ident",
				Admin:       &admin,
			}))

			By("waiting for the operator to push the change")
			waitForStatusField("pocketiduser", userName, userNS, ".status.isAdmin", "true")
			waitForStatusField("pocketiduser", userName, userNS, ".status.userID", declaredID)

			By("verifying Pocket-ID returns the updated state under the same ID")
			user := getUserFromPocketID(declaredID)
			Expect(user.ID).To(Equal(declaredID), "the user ID must not change on update")
			Expect(user.DisplayName).To(Equal("Renamed Ident"))
			Expect(user.IsAdmin).To(BeTrue())
		})

		It("should adopt the same Pocket-ID user when the resource is recreated", func() {
			By("deleting the resource (the Pocket-ID user is retained without the delete annotation)")
			kubectlDelete("pocketiduser", userName, userNS)
			waitForResourceDeleted("pocketiduser", userName, userNS)

			By("verifying the user still exists in Pocket-ID")
			Expect(getUserFromPocketID(declaredID).ID).To(Equal(declaredID))

			By("recreating the resource with the same declared ID but a different username")
			createUser(UserOptions{
				Name:      userName,
				UserID:    declaredID,
				Username:  userName + "-readopted",
				Email:     userEmail,
				FirstName: firstName,
				LastName:  lastName,
			})
			waitForReady("pocketiduser", userName, userNS)

			By("verifying the existing user was adopted rather than a second one created")
			waitForStatusField("pocketiduser", userName, userNS, ".status.userID", declaredID)
			Eventually(func(g Gomega) {
				g.Expect(kubectlGetSecretData(userName+"-user-data", userNS, "username")).
					To(Equal(userName + "-readopted"))
			}, 2*time.Minute, 2*time.Second).Should(Succeed())

			user := getUserFromPocketID(declaredID)
			Expect(user.ID).To(Equal(declaredID))
			Expect(user.Username).To(Equal(userName + "-readopted"))
		})

		AfterAll(func() {
			kubectlDelete("pocketiduser", userName, userNS)
			waitForResourceDeleted("pocketiduser", userName, userNS)
		})
	})

	Context("Autogenerated user ID", func() {
		const userName = "test-autogen-userid"

		It("should let Pocket-ID assign the ID when spec.userID is unset", func() {
			createUser(UserOptions{Name: userName, Email: "autogen-id@example.com"})
			waitForReady("pocketiduser", userName, userNS)

			statusUserID := waitForStatusFieldNotEmpty("pocketiduser", userName, userNS, ".status.userID")
			Expect(statusUserID).NotTo(Equal(userName),
				"status.userID should come from Pocket-ID, not be inferred from the resource name")

			By("verifying Pocket-ID returns the user under the autogenerated ID")
			user := getUserFromPocketID(statusUserID)
			Expect(user.ID).To(Equal(statusUserID))
			Expect(user.Username).To(Equal(userName))
		})

		AfterAll(func() {
			kubectlDelete("pocketiduser", userName, userNS)
			waitForResourceDeleted("pocketiduser", userName, userNS)
		})
	})

})
