name: Zizmor

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/**"
      - ".github/actions/**"
      - ".mise.toml"
      - "mise.lock"
  pull_request:
    paths:
      - ".github/workflows/**"
      - ".github/actions/**"
      - ".mise.toml"
      - "mise.lock"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  zizmor:
    name: Audit workflows
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Setup mise
        uses: jdx/mise-action@94c60b39bc2d90ab2f9bab27f38d3cc4812c1834 # v5.1.0
        with:
          # renovate: datasource=github-releases depName=jdx/mise
          version: "2026.10.0"
          install_args: zizmor

      - name: Run zizmor
        env:
          GH_TOKEN: ${{ github.token }}
        run: zizmor --format=github .
