name: Zizmor

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/**"
      - ".github/actions/**"
  pull_request:
    paths:
      - ".github/workflows/**"
      - ".github/actions/**"
  workflow_dispatch:

jobs:
  zizmor:
    uses: aclerici38/workflows/.github/workflows/zizmor.yaml@main
    permissions:
      contents: read
      security-events: write
